name = "Wheel Redirect"
handle = "wheel-redirect"

type = "ui_extension"
api_version = "2024-07"

# Where this extension renders
[[extension_points]]
target = "purchase.thank-you.block.render"
module = "./dist/main.js"

[build]
command = "npm run build"
path = "dist/main.js"

[ui]
surface = "checkout" 