import React from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';

const GameplayPage = () => {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold mb-6">Gameplay Overview</h1>
      <h1 className="text-3xl font-bold mb-6">Gameplay</h1>
      <p className="mb-4">
        Elemental Masters is an exciting 2-player trading card game where you harness the power of the elements to defeat your opponents. An average game lasts 20-25 minutes.
      </p>
      <div className="mb-6 flex flex-wrap gap-4">
        <Link to="/rules">
          <Button>View Full Rules</Button>
        </Link>
        <Button onClick={() => window.open('/rulebook.pdf', '_blank')}>
          <Download className="mr-2 h-4 w-4" /> Download Rulebook PDF
        </Button>
        <Link to="/learn-to-play">
          <Button>Learn More</Button>
        </Link>
      </div>
      <h2 className="text-2xl font-semibold mb-4">Quick Overview</h2>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>Build a deck of 40 cards, combining different elements and strategies.</li>
        <li>Start with 3 shields (1 of each tier) and draw 5 cards.</li>
        <li>Generate and use essence as a resource to play cards and activate abilities.</li>
        <li>Take turns playing creatures, runes, and counters, and engaging in combat.</li>
        <li>Destroy your opponent's shields and deplete their health points to zero to win!</li>
        <li>Alternatively, win by collecting all 4 ancient elemental cards and playing the "Ancient Sigil" rune.</li>
      </ul>
      <h2 className="text-2xl font-semibold mb-4">Key Game Elements</h2>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li><strong>Creatures:</strong> Main battling units from 4 elements (Air, Water, Fire, Earth) and 6 combinational elements for Dragons.</li>
        <li><strong>Runes:</strong> Types include Normal, Equipments, and Instants. Have a variety of effects that can support your strategy or disrupt your opponent's. Can be activated the turn you place them.</li>
        <li><strong>Counters:</strong> Can be activated during either player's turn, often in response to specific actions. Provide surprise elements and ways to counter your opponent's moves. Must be Set face-down for one turn before they can be activated.</li>
        <li><strong>Shields:</strong> Your last line of defense, providing a choice between powerful effects when broken.</li>
        <li><strong>Essence:</strong> Resource generated by creatures, used to play cards and activate abilities. Treated as an in-game currency.</li>
      </ul>
      <p className="mb-4">
        For a complete understanding of the game mechanics, turn structure, combat system, and special features, please refer to the full rulebook.
      </p>
      <h2 className="text-2xl font-semibold mb-4">Gameplay Modes</h2>
      <ul className="list-disc list-inside mb-6">
        <li>Casual: No restrictions on card usage.</li>
        <li>Competitive: Follow card restriction guidelines in the rulebook.</li>
      </ul>
      <div className="mt-8">
        <Link to="/gameplay/battle-simulation">
          <Button>Try Battle Simulation</Button>
        </Link>
      </div>
    </div>
  );
};

export default GameplayPage;